import { jsPDF } from 'jspdf'

// Shared PDF report styling (Cashcrow green tables + branded header).
// Used by the Part and Supplier "Download PDF" reports so they look identical.

export const BRAND_GREEN: [number, number, number] = [38, 80, 53]   // #265035
const ROW_LIGHT: [number, number, number] = [240, 247, 241]

/**
 * Adds the branded header: centered Cashcrow logo (text fallback), a divider,
 * and a metadata row (optional "Generated by" + timestamp). Returns the y to
 * continue drawing from.
 */
export async function addReportHeader(
    doc: jsPDF,
    opts: { pageWidth: number; marginX: number; userName?: string }
): Promise<number> {
    const { pageWidth, marginX, userName } = opts
    let y = 12

    try {
        const logo = new Image()
        logo.src = '/Cashcrow_Logo_Mobile.png'
        await logo.decode()
        const h = 18
        const w = h * (logo.width / logo.height)
        doc.addImage(logo, 'PNG', (pageWidth - w) / 2, 10, w, h)
        y = 10 + h + 6
    } catch {
        doc.setFontSize(22); doc.setFont('helvetica', 'bold')
        doc.setTextColor(BRAND_GREEN[0], BRAND_GREEN[1], BRAND_GREEN[2])
        doc.text('Cashcrow', pageWidth / 2, 18, { align: 'center' })
        y = 26
    }

    doc.setDrawColor(210, 210, 210)
    doc.line(marginX, y, pageWidth - marginX, y)

    y += 8
    doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.setTextColor(110, 110, 110)
    if (userName) doc.text(`Generated by: ${userName}`, marginX, y)
    doc.text(new Date().toLocaleString(), pageWidth - marginX, y, { align: 'right' })

    return y
}

export function drawSectionTitle(doc: jsPDF, text: string, x: number, y: number): number {
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(BRAND_GREEN[0], BRAND_GREEN[1], BRAND_GREEN[2])
    doc.text(text, x, y)
    return y + 4
}

export function drawTable(
    doc: jsPDF,
    opts: { startY: number; head: string[]; rows: (string | number)[][]; colWidths: number[]; marginX: number }
): number {
    const { head, rows, colWidths, marginX } = opts
    const rowH = 8
    const pageH = doc.internal.pageSize.getHeight()
    const totalW = colWidths.reduce((a, b) => a + b, 0)
    let y = opts.startY

    const header = () => {
        doc.setFillColor(BRAND_GREEN[0], BRAND_GREEN[1], BRAND_GREEN[2])
        doc.rect(marginX, y, totalW, rowH, 'F')
        doc.setTextColor(255, 255, 255)
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(9)
        let x = marginX
        head.forEach((h, i) => { doc.text(h, x + 3, y + rowH - 2.6); x += colWidths[i] })
        y += rowH
    }

    header()
    rows.forEach((row, ri) => {
        if (y + rowH > pageH - 18) { doc.addPage(); y = 20; header() }
        if (ri % 2 === 0) {
            doc.setFillColor(ROW_LIGHT[0], ROW_LIGHT[1], ROW_LIGHT[2])
            doc.rect(marginX, y, totalW, rowH, 'F')
        }
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(8.5)
        doc.setTextColor(35, 35, 35)
        let x = marginX
        row.forEach((cell, i) => {
            const clipped = doc.splitTextToSize(String(cell ?? ''), colWidths[i] - 4)[0] ?? ''
            doc.text(clipped, x + 3, y + rowH - 2.6)
            x += colWidths[i]
        })
        y += rowH
    })

    doc.setDrawColor(220, 220, 220)
    doc.line(marginX, y, marginX + totalW, y)
    return y
}

export function ensureSpace(doc: jsPDF, y: number, needed: number): number {
    const pageH = doc.internal.pageSize.getHeight()
    if (y + needed > pageH - 18) { doc.addPage(); return 20 }
    return y
}
