'use client'

import React, { useState, useRef } from 'react'
import { Edit3, Download, Trash2, Loader2, AlertTriangle, X, FileText, ChevronDown, Upload, ExternalLink as ExternalLinkIcon } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { jsPDF } from 'jspdf'
import { toast } from 'sonner'
import { Product } from '@/types/product'
import { deleteProduct, updateProduct } from '@/actions/products'
import EditProductForm from '@/components/admin/inventory/edit-product-form'
import { getStockStatus } from '@/components/shared/inventory/product-card'

interface ProductDetailActionsProps {
    product: Product
    logs: any[]
    userName: string
    isAdmin?: boolean
}

export default function ProductDetailActions({ product, logs, userName, isAdmin = false }: ProductDetailActionsProps) {
    const router = useRouter()
    const fileInputRef = useRef<HTMLInputElement>(null)
    const [showEditModal, setShowEditModal] = useState(false)
    const [isDeleting, setIsDeleting] = useState(false)
    const [isUploading, setIsUploading] = useState(false)
    const [showDeleteConfirm, setShowDeleteConfirm] = useState(false)
    const [deleteError, setDeleteError] = useState('')
    const [showDSMenu, setShowDSMenu] = useState(false)

    const handleDataSheetClick = () => {
        if (product.data_sheet_url) {
            setShowDSMenu(!showDSMenu)
        } else if (isAdmin) {
            fileInputRef.current?.click()
        }
    }

    const handleDataSheetUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0]
        if (!file) return

        setIsUploading(true)
        const formData = new FormData()
        formData.append('data_sheet', file)
        formData.append('name', product.name) // Required for updateProduct validation
        
        try {
            const result = await updateProduct(product.id, formData)
            if (result.success) {
                setShowDSMenu(false)
                toast.success('Data sheet uploaded successfully')
                router.refresh()
            } else {
                toast.error(result.error || 'Failed to upload data sheet')
            }
        } catch (err) {
            console.error('Data sheet upload error:', err)
        } finally {
            setIsUploading(false)
        }
    }

    const handleDownloadPDF = () => {
        const doc = new jsPDF()
        const pageWidth = doc.internal.pageSize.getWidth()
        const timestamp = new Date().toLocaleString()

        // 1. Branding Header
        doc.setFontSize(24)
        doc.setFont('helvetica', 'bold')
        doc.text('Cashcrow', pageWidth / 2, 20, { align: 'center' })
        
        doc.setDrawColor(200, 200, 200)
        doc.line(20, 25, pageWidth - 20, 25)

        // 2. Metadata (Left Side)
        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(100, 100, 100)
        doc.text(`Generated by: ${userName}`, 20, 35)
        doc.text(`Time: ${timestamp}`, 20, 40)

        // 3. Product Info
        doc.setFontSize(18)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(0, 0, 0)
        doc.text(product.name, 20, 55)
        
        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(120, 120, 120)
        doc.text(`SKU: ${product.sku}  |  Category: ${product.category}`, 20, 62)

        // 4. Current Metrics
        doc.setFontSize(12)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(0, 0, 0)
        doc.text('CURRENT METRICS', 20, 75)
        
        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        const status = getStockStatus(product.quantity || 0, product.min_stock_level || 0)
        
        let y = 85
        const metrics = [
            { label: 'Current Stock', value: `${product.quantity} ${product.unit_of_measurement || 'units'}` },
            { label: 'Location', value: `Shelf ${product.shelf_code}, Box ${product.box_code}` },
            { label: 'Reorder Level', value: `${product.min_stock_level} units` },
            { label: 'Status', value: status.label }
        ]
        
        metrics.forEach(m => {
            doc.text(`${m.label}:`, 20, y)
            doc.setFont('helvetica', 'bold')
            doc.text(String(m.value), 60, y)
            doc.setFont('helvetica', 'normal')
            y += 7
        })

        // 5. Movement History
        y += 10
        doc.setFontSize(12)
        doc.setFont('helvetica', 'bold')
        doc.text('MOVEMENT HISTORY (Recent)', 20, y)
        y += 10
        
        doc.setFontSize(9)
        doc.setTextColor(80, 80, 80)
        doc.text('Date', 20, y)
        doc.text('Type', 50, y)
        doc.text('Qty', 70, y)
        doc.text('Purpose', 90, y)
        doc.text('Used By', 160, y)
        
        y += 2
        doc.line(20, y, pageWidth - 20, y)
        y += 6

        doc.setFont('helvetica', 'normal')
        doc.setTextColor(0, 0, 0)
        
        logs.slice(0, 15).forEach(log => {
            if (y > 270) { doc.addPage(); y = 20; }
            doc.text(log.date || 'N/A', 20, y)
            doc.text(log.type || 'N/A', 50, y)
            doc.text(`${log.sign}${log.quantity}`, 70, y)
            doc.text(log.purpose || 'Stock Update', 90, y, { maxWidth: 65 })
            doc.text(log.takenBy || 'System', 160, y, { maxWidth: 30 })
            y += 8
        })

        // 6. Supplier Info
        y += 10
        if (y > 250) { doc.addPage(); y = 20; }
        doc.setFontSize(12)
        doc.setFont('helvetica', 'bold')
        doc.text('SUPPLIERS', 20, y)
        y += 10
        
        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        if (product.vendors && product.vendors.length > 0) {
            product.vendors.forEach((v: any) => {
                doc.text(`- ${v.name}:`, 20, y)
                doc.setFont('helvetica', 'bold')
                doc.text(`Rs. ${v.fund}`, 80, y)
                doc.setFont('helvetica', 'normal')
                y += 7
            })
        } else {
            doc.text('No suppliers linked to this product.', 20, y)
        }

        doc.save(`Cashcrow_Report_${product.sku}.pdf`)
    }

    const handleDelete = async () => {
        setIsDeleting(true)
        setDeleteError('')
        try {
            const result = await deleteProduct(product.id)
            if (result.success) {
                toast.success('Part deleted successfully')
                const basePath = window.location.pathname.includes('/admin') ? '/admin/parts' : '/member/parts'
                router.push(basePath)
                router.refresh()
            } else {
                setDeleteError(result.error || 'Failed to delete product')
                toast.error(result.error || 'Failed to delete product')
            }
        } catch (err) {
            setDeleteError('An unexpected error occurred during deletion.')
        } finally {
            setIsDeleting(false)
        }
    }

    return (
        <>
            <div className="flex flex-wrap items-center gap-3">
                {isAdmin && (
                    <button
                        onClick={() => setShowEditModal(true)}
                        className="flex items-center gap-2 px-4 py-2.5 bg-[#265035] border border-[#2f6443] text-white rounded-xl text-sm font-bold hover:bg-[#2f6443] transition-all shadow-sm active:scale-95"
                    >
                        <Edit3 className="w-4 h-4" />
                        Edit Details
                    </button>
                )}

                <div className="relative">
                    <button
                        onClick={handleDataSheetClick}
                        disabled={isUploading}
                        className="flex items-center gap-2 px-4 py-2.5 bg-[var(--color-cashcrow-lightgreen)] text-white rounded-xl text-sm font-bold hover:opacity-90 transition-all shadow-sm active:scale-95"
                    >
                        {isUploading ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileText className="w-4 h-4" />}
                        {product.data_sheet_url ? 'Data Sheet' : 'Upload Data Sheet'}
                        {product.data_sheet_url && <ChevronDown className={`w-4 h-4 transition-transform ${showDSMenu ? 'rotate-180' : ''}`} />}
                    </button>

                    {showDSMenu && (
                        <div className="absolute top-full left-0 mt-2 w-48 bg-white rounded-xl shadow-xl border border-slate-100 py-2 z-50 animate-in fade-in slide-in-from-top-2">
                            <button
                                onClick={() => {
                                    window.open(product.data_sheet_url as string, '_blank')
                                    setShowDSMenu(false)
                                }}
                                className="w-full flex items-center gap-3 px-4 py-2 text-sm text-slate-700 hover:bg-slate-50 transition-colors"
                            >
                                <ExternalLinkIcon className="w-4 h-4 text-[var(--color-cashcrow-lightgreen)]" />
                                Show Current
                            </button>
                            {isAdmin && (
                                <button
                                    onClick={() => {
                                        fileInputRef.current?.click()
                                        setShowDSMenu(false)
                                    }}
                                    className="w-full flex items-center gap-3 px-4 py-2 text-sm text-slate-700 hover:bg-slate-50 transition-colors"
                                >
                                    <Upload className="w-4 h-4 text-[var(--color-cashcrow-lightgreen)]" />
                                    Upload New
                                </button>
                            )}
                        </div>
                    )}
                </div>

                <input 
                    type="file" 
                    ref={fileInputRef} 
                    onChange={handleDataSheetUpload} 
                    className="hidden" 
                    accept=".pdf,image/*" 
                />

                <button
                    onClick={handleDownloadPDF}
                    className="flex items-center gap-2 px-4 py-2.5 bg-white border border-slate-200 text-slate-700 rounded-xl text-sm font-bold hover:bg-slate-50 transition-all shadow-sm active:scale-95"
                >
                    <Download className="w-4 h-4" />
                    Download PDF
                </button>

                {isAdmin && (
                    <button
                        onClick={() => setShowDeleteConfirm(true)}
                        className="flex items-center gap-2 px-4 py-2.5 bg-red-50 border border-red-100 text-red-600 rounded-xl text-sm font-bold hover:bg-red-100 hover:border-red-200 transition-all shadow-sm active:scale-95"
                    >
                        <Trash2 className="w-4 h-4" />
                        Delete Part
                    </button>
                )}
            </div>

            {/* Edit Modal */}
            {showEditModal && (
                <div className="fixed inset-0 z-[70] flex items-center justify-center p-4">
                    <div 
                        className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm" 
                        onClick={() => setShowEditModal(false)}
                    />
                    <div className="relative w-full max-w-4xl max-h-[90vh] overflow-y-auto bg-white rounded-2xl shadow-2xl border border-slate-200 animate-in zoom-in-95 duration-200">
                        <button
                            onClick={() => setShowEditModal(false)}
                            className="absolute top-4 right-4 p-2 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-600 transition-colors z-10"
                        >
                            <X className="w-5 h-5" />
                        </button>
                        <div className="p-8">
                            <EditProductForm
                                product={{ ...product, image_url: product?.image_url || undefined } as any}
                                onSuccess={() => {
                                    setShowEditModal(false)
                                    router.refresh()
                                }}
                                onCancel={() => setShowEditModal(false)}
                            />
                        </div>
                    </div>
                </div>
            )}

            {/* Delete Confirmation Modal */}
            {showDeleteConfirm && (
                <div className="fixed inset-0 z-[70] flex items-center justify-center p-4">
                    <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm" />
                    <div className="relative w-full max-w-md bg-white rounded-2xl shadow-2xl border p-8 animate-in zoom-in-95 duration-200">
                        <div className="w-16 h-16 bg-red-50 rounded-full flex items-center justify-center mx-auto mb-6">
                            <AlertTriangle className="w-8 h-8 text-red-600" />
                        </div>
                        <h3 className="text-xl font-bold text-center text-slate-900 mb-2">Delete this part?</h3>
                        <p className="text-slate-500 text-center text-sm mb-8">
                            This action is permanent and will remove <span className="font-bold text-slate-800">{product.name}</span> from the system.
                        </p>

                        {deleteError && (
                            <div className="mb-6 p-4 bg-red-50 border border-red-100 text-red-600 text-sm rounded-xl font-medium">
                                {deleteError}
                            </div>
                        )}

                        <div className="flex flex-col gap-3">
                            <button
                                onClick={handleDelete}
                                disabled={isDeleting}
                                className="w-full py-3 bg-red-600 hover:bg-red-700 text-white rounded-xl font-bold transition-all disabled:opacity-50 flex items-center justify-center gap-2"
                            >
                                {isDeleting ? <Loader2 className="w-4 h-4 animate-spin" /> : 'Confirm Deletion'}
                            </button>
                            <button
                                onClick={() => {
                                    setShowDeleteConfirm(false)
                                    setDeleteError('')
                                }}
                                disabled={isDeleting}
                                className="w-full py-3 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl font-bold transition-all"
                            >
                                Cancel
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </>
    )
}
