'use client'

import { FileText, Package, Wrench } from 'lucide-react'
import { QuoteRow, QuoteStatus, QuoteType } from '@/types/quote'

interface QuotesTableProps {
    quotes: QuoteRow[]
}

function getStatusStyle(status: string) {
    switch (status) {
        case QuoteStatus.APPROVED:
            return { bg: 'bg-emerald-100', text: 'text-emerald-700', ring: 'ring-emerald-200' }
        case QuoteStatus.ORDERED:
            return { bg: 'bg-blue-100', text: 'text-blue-700', ring: 'ring-blue-200' }
        case QuoteStatus.DENIED:
            return { bg: 'bg-red-100', text: 'text-red-700', ring: 'ring-red-200' }
        case QuoteStatus.PENDING:
        default:
            return { bg: 'bg-amber-100', text: 'text-amber-700', ring: 'ring-amber-200' }
    }
}

function getTypeStyle(type: string) {
    if (type === QuoteType.SERVICE) {
        return { label: 'Service', icon: Wrench, bg: 'bg-amber-50', text: 'text-amber-700', ring: 'ring-amber-200' }
    }
    return { label: 'Product', icon: Package, bg: 'bg-emerald-50', text: 'text-emerald-700', ring: 'ring-emerald-200' }
}

function getAuthorName(profile: QuoteRow['generated_by_profile']) {
    if (!profile) return null
    const name = `${profile.first_name ?? ''} ${profile.last_name ?? ''}`.trim()
    return name || null
}

function formatDate(value: string) {
    try {
        return new Date(value).toLocaleDateString('en-GB', {
            day: '2-digit',
            month: 'short',
            year: 'numeric',
        })
    } catch {
        return value
    }
}

export default function QuotesTable({ quotes }: QuotesTableProps) {
    if (quotes.length === 0) {
        return (
            <div className="bg-white border border-slate-200 rounded-2xl shadow-sm p-12 text-center">
                <FileText className="w-12 h-12 text-slate-300 mx-auto mb-4" />
                <h3 className="text-lg font-bold text-slate-700 mb-2">No Quotes Yet</h3>
                <p className="text-slate-500 text-sm">Quotes you generate will appear here. Use the &ldquo;Generate Quote&rdquo; button to create one.</p>
            </div>
        )
    }

    return (
        <div className="bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden">
            <div className="bg-slate-50 border-b border-slate-200 px-3 md:px-6 py-3 md:py-4 flex items-center gap-2 flex-wrap">
                <FileText className="w-4 h-4 md:w-5 md:h-5 text-[var(--color-cashcrow-primary)]" />
                <h3 className="text-xs md:text-sm font-bold uppercase tracking-wider text-slate-700">Quotes</h3>
                <span className="ml-auto text-xs font-bold bg-[var(--color-cashcrow-primary)] text-white px-2 py-0.5 md:px-2.5 md:py-1 rounded-full">
                    {quotes.length}
                </span>
            </div>
            <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse min-w-0 table-auto">
                    <thead>
                        <tr className="bg-slate-50/50 text-slate-500 text-[10px] uppercase tracking-[0.15em] font-black border-b border-slate-100">
                            <th className="w-[40%] px-2 md:px-6 py-3 md:py-4">Quote</th>
                            <th className="hidden md:table-cell px-2 md:px-6 py-3 md:py-4">Type</th>
                            <th className="hidden lg:table-cell px-2 md:px-6 py-3 md:py-4">Generated by</th>
                            <th className="hidden lg:table-cell px-2 md:px-6 py-3 md:py-4">Generated at</th>
                            <th className="px-2 md:px-6 py-3 md:py-4 text-right">Status</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                        {quotes.map((quote) => {
                            const name = quote.name || quote.request_id || '—'
                            const type = getTypeStyle(quote.quote_type || QuoteType.PRODUCT)
                            const TypeIcon = type.icon
                            const author = getAuthorName(quote.generated_by_profile)
                            const status = getStatusStyle(quote.status)

                            return (
                                <tr key={quote.id} className="hover:bg-slate-50/50 transition-colors group">
                                    <td className="px-3 md:px-6 py-4">
                                        <div className="flex items-center gap-3">
                                            <div className="w-10 h-10 rounded-lg bg-slate-100 flex items-center justify-center shrink-0">
                                                <TypeIcon className="w-5 h-5 text-slate-400" />
                                            </div>
                                            <div className="min-w-0 flex-1">
                                                <p className="font-semibold text-slate-900 truncate text-sm">{name}</p>
                                                {quote.request_id && quote.name && (
                                                    <span className="text-xs text-slate-500 font-mono">{quote.request_id}</span>
                                                )}
                                            </div>
                                        </div>
                                    </td>
                                    <td className="px-3 md:px-6 py-4 hidden md:table-cell">
                                        <span className={`inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider ${type.bg} ${type.text} ring-1 ${type.ring}`}>
                                            <TypeIcon className="w-3 h-3" />
                                            {type.label}
                                        </span>
                                    </td>
                                    <td className="px-3 md:px-6 py-4 hidden lg:table-cell">
                                        <span className="text-sm text-slate-700 font-medium">{author || '—'}</span>
                                    </td>
                                    <td className="px-3 md:px-6 py-4 hidden lg:table-cell">
                                        <span className="text-sm text-slate-600">{formatDate(quote.created_at)}</span>
                                    </td>
                                    <td className="px-3 md:px-6 py-4 text-right">
                                        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider ${status.bg} ${status.text} ring-1 ${status.ring}`}>
                                            {quote.status || QuoteStatus.PENDING}
                                        </span>
                                    </td>
                                </tr>
                            )
                        })}
                    </tbody>
                </table>
            </div>
        </div>
    )
}
